CREATE TABLE heberg_tourisme_VAR (
    VAR_ID VARCHAR(9) CHARACTER SET utf8,
    VAR_LIB VARCHAR(76) CHARACTER SET utf8,
    VAR_LIB_LONG VARCHAR(129) CHARACTER SET utf8
);
INSERT INTO heberg_tourisme_VAR VALUES ('CODGEO','CODGEO','Code du département suivi du numéro de commune ou du numéro d''arrondissement municipal');
INSERT INTO heberg_tourisme_VAR VALUES ('LIBGEO','Libellé commune ou ARM','Libellé de la commune ou de l''arrondissement municipal pour Paris Lyon et Marseille');
INSERT INTO heberg_tourisme_VAR VALUES ('REG','Région','Région');
INSERT INTO heberg_tourisme_VAR VALUES ('REG2016','Région 2016','Région 2016');
INSERT INTO heberg_tourisme_VAR VALUES ('DEP','Département','Département');
INSERT INTO heberg_tourisme_VAR VALUES ('HT15','Hôtels en 2015','Nombre d''hôtels en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT015','Hôtels non classés en 2015','Nombre d''hôtels non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT115','Hôtels classés 1 étoile en 2015','Nombre d''hôtels classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT215','Hôtels classés 2 étoiles en 2015','Nombre d''hôtels classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT315','Hôtels classés 3 étoiles en 2015','Nombre d''hôtels classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT415','Hôtels classés 4 étoiles en 2015','Nombre d''hôtels classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HT515','Hôtels classés 5 étoiles en 2015','Nombre d''hôtels classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH15','Chambres dans hôtels en 2015','Nombre de chambres dans les hôtels en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH015','Chambres dans hôtels non classés en 2015','Nombre de chambres dans les hôtels non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH115','Chambres dans hôtels classés 1 étoile en 2015','Nombre de chambres dans les hôtels classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH215','Chambres dans hôtels classés 2 étoiles en 2015','Nombre de chambres dans les hôtels classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH315','Chambres dans hôtels classés 3 étoiles en 2015','Nombre de chambres dans les hôtels classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH415','Chambres dans hôtels classés 4 étoiles en 2015','Nombre de chambres dans les hôtels classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('HTCH515','Chambres dans hôtels classés 5 étoiles en 2015','Nombre de chambres dans les hôtels classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG15','Campings en 2015','Nombre de terrains de camping en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG015','Campings non classés en 2015','Nombre de terrains de camping non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG115','Campings classés 1 étoile en 2015','Nombre de terrains de camping classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG215','Campings classés 2 étoiles en 2015','Nombre de terrains de camping classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG315','Campings classés 3 étoiles en 2015','Nombre de terrains de camping classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG415','Campings classés 4 étoiles en 2015','Nombre de terrains de camping classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPG515','Campings classés 5 étoiles en 2015','Nombre de terrains de camping classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE15','Emplacements de camping en 2015','Nombre d''emplacements de camping en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE015','Emplacements camping non classés en 2015','Nombre d''emplacements de camping non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE115','Emplacements camping classés 1 étoile en 2015','Nombre d''emplacements de camping classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE215','Emplacements camping classés 2 étoiles en 2015','Nombre d''emplacements de camping classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE315','Emplacements camping classés 3 étoiles en 2015','Nombre d''emplacements de camping classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE415','Emplacements camping classés 4 étoiles en 2015','Nombre d''emplacements de camping classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGE515','Emplacements camping classés 5 étoiles en 2015','Nombre d''emplacements de camping classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL15','Emplacements loués à l''année en 2015','Nombre total d''emplacements loués à l''année en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL015','Emplacements loués à l''année campings non classés en 2015','Nombre total d''emplacements loués à l''année campings non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL115','Emplacements loués à l''année campings classés 1 étoile en 2015','Nombre total d''emplacements loués à l''année campings classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL215','Emplacements loués à l''année campings classés 2 étoiles en 2015','Nombre total d''emplacements loués à l''année campings classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL315','Emplacements loués à l''année campings classés 3 étoiles en 2015','Nombre total d''emplacements loués à l''année campings classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL415','Emplacements loués à l''année campings classés 4 étoiles en 2015','Nombre total d''emplacements loués à l''année campings classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEL515','Emplacements loués à l''année campings classés 5 étoiles en 2015','Nombre total d''emplacements loués à l''année campings classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO15','Emplacements offerts clientèle de passage dans campings en 2015','Nombre total d''emplacements offerts clientèle de passage dans campings en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO015','Emplacements offerts clientèle de passage campings non classés en 2015','Nombre total d''emplacements offerts clientèle de passage campings non classés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO115','Emplacements offerts clientèle de passage campings classés 1 étoile en 2015','Nombre total d''emplacements offerts clientèle de passage campings classés 1 étoile en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO215','Emplacements offerts clientèle de passage campings classés 2 étoiles en 2015','Nombre total d''emplacements offerts clientèle de passage campings classés 2 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO315','Emplacements offerts clientèle de passage campings classés 3 étoiles en 2015','Nombre total d''emplacements offerts clientèle de passage campings classés 3 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO415','Emplacements offerts clientèle de passage campings classés 4 étoiles en 2015','Nombre total d''emplacements offerts clientèle de passage campings classés 4 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('CPGEO515','Emplacements offerts clientèle de passage campings classés 5 étoiles en 2015','Nombre total d''emplacements offerts clientèle de passage campings classés 5 étoiles en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('VV15','Villages vacances en 2015','Nombre de Villages vacances-Maisons familiales en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('VVUH15','Unités d''hébergements dans Villages vacances en 2015','Nombre total d''unités d''hébergements dans les Villages vacances - Maisons familiales en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('VVLIT15','Lits dans Villages vacances en 2015','Nombre total de places lit dans les Villages vacances - Maisons familiales en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('RT15','Résidences de tourisme en 2015','Nombre de résidences de tourisme et hébergements assimilés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('RTUH15','Unités d''hébergements dans Résidences de tourisme en 2015','Nombre total d''unités d''hébergements dans les résidences de tourisme et hébergements assimilés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('RTLIT15','Lits dans Résidences de tourisme en 2015','Nombre total de places lit dans les résidences de tourisme et hébergements assimilés en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('AJCS15','Auberges de jeunesse - Centres sportifs en 2015','Nombre d''auberges de jeunesse - Centres internationaux de séjour et centres sportifs en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('AJCSUH15','Unités d''hébergements dans Auberges de jeunesse - Centres sportifs en 2015','Nombre total d''unités d''hébergements dans les auberges de jeunesse - Centres internationaux de séjour et centres sportifs en 2015');
INSERT INTO heberg_tourisme_VAR VALUES ('AJCSLIT15','Lits dans Auberges de jeunesse - Centre sportif en 2015','Nombre total de places lit dans les auberges de jeunesse - Centres internationaux de séjour et centres sportifs en 2015');
